services:
  kodi-training:
    container_name: kodi-training
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8086:8086"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./thumbnails:/app/thumbnails
      - ./aws-config.json:/app/aws-config.json
      - ./pi-config.json:/app/pi-config.json
    env_file:
      - .env
    restart: unless-stopped
